### ISSUE TITLE
Using mvc.info()

### ISSUE THREAD

**Issue by VictorOmondiCDS** [Clemo97/working-with-missing-data#1]
Using `mvc.info()` will generate a Concise summary of a of the DataFrame.
Check out [Pandas Documentation](https://pandas.pydata.org/pandas-docs) on the [`.info()` method](https://pandas.pydata.org/pandas-docs/version/0.22.0/generated/pandas.DataFrame.info.html#pandas-dataframe-info)

**Comment by Clemo97** [comment]
Thanks, will update the notebook.
